apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: afra-divar-bot
  labels:
    app.kubernetes.io/name: afra-divar-bot
    app.kubernetes.io/part-of: afra-automation-platform
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: afra-divar-bot
  minReplicas: 3
  maxReplicas: 50
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 75
